version: "3.1"

volumes:
  app_node_modules:

services:

  cyberpunk_db:
    container_name: cyberpunk_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --default-authentication-plugin=mysql_native_password
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./mysqlVars.env
    environment:
      MYSQL_ROOT_PASSWORD: root

  cyberpunk_app:
    container_name: cyberpunk_app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - cyberpunk_db
    env_file:
      - ./mysqlVars.env
      - ./discord.env
    environment:
      DB_HOST: cyberpunk_db
    volumes:
      - app_node_modules:/home/cyberunk/app/node_modules/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
