version: "3.1"

volumes:
  app_node_modules:

services:

  db:
    container_name: cyberpunk_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./mysqlVars.env
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    container_name: cyberpunk_app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./mysqlVars.env
      - ./discord.env
    environment:
      DB_HOST: db
    volumes:
      - app_node_modules:/home/cyberunk/app/node_modules/
